package iso3166

// Code generated by tools/codegen/iso3166-1. DO NOT EDIT.

var (
	AA = Alpha2Code{
		Code:    "AA",
		Status:  2,
		Country: "",
	}
	AB = Alpha2Code{
		Code:    "AB",
		Status:  7,
		Country: "",
	}
	AC = Alpha2Code{
		Code:    "AC",
		Status:  3,
		Country: "Ascension Island",
	}
	AD = Alpha2Code{
		Code:    "AD",
		Status:  1,
		Country: "Andorra",
	}
	AE = Alpha2Code{
		Code:    "AE",
		Status:  1,
		Country: "United Arab Emirates (the)",
	}
	AF = Alpha2Code{
		Code:    "AF",
		Status:  1,
		Country: "Afghanistan",
	}
	AG = Alpha2Code{
		Code:    "AG",
		Status:  1,
		Country: "Antigua and Barbuda",
	}
	AH = Alpha2Code{
		Code:    "AH",
		Status:  7,
		Country: "",
	}
	AI = Alpha2Code{
		Code:    "AI",
		Status:  1,
		Country: "Anguilla",
	}
	AJ = Alpha2Code{
		Code:    "AJ",
		Status:  7,
		Country: "",
	}
	AK = Alpha2Code{
		Code:    "AK",
		Status:  7,
		Country: "",
	}
	AL = Alpha2Code{
		Code:    "AL",
		Status:  1,
		Country: "Albania",
	}
	AM = Alpha2Code{
		Code:    "AM",
		Status:  1,
		Country: "Armenia",
	}
	AN = Alpha2Code{
		Code:    "AN",
		Status:  4,
		Country: "Netherlands Antilles",
	}
	AO = Alpha2Code{
		Code:    "AO",
		Status:  1,
		Country: "Angola",
	}
	AP = Alpha2Code{
		Code:    "AP",
		Status:  5,
		Country: "African Regional Industrial Property Organization",
	}
	AQ = Alpha2Code{
		Code:    "AQ",
		Status:  1,
		Country: "Antarctica",
	}
	AR = Alpha2Code{
		Code:    "AR",
		Status:  1,
		Country: "Argentina",
	}
	AS = Alpha2Code{
		Code:    "AS",
		Status:  1,
		Country: "American Samoa",
	}
	AT = Alpha2Code{
		Code:    "AT",
		Status:  1,
		Country: "Austria",
	}
	AU = Alpha2Code{
		Code:    "AU",
		Status:  1,
		Country: "Australia",
	}
	AV = Alpha2Code{
		Code:    "AV",
		Status:  7,
		Country: "",
	}
	AW = Alpha2Code{
		Code:    "AW",
		Status:  1,
		Country: "Aruba",
	}
	AX = Alpha2Code{
		Code:    "AX",
		Status:  1,
		Country: "Åland Islands",
	}
	AY = Alpha2Code{
		Code:    "AY",
		Status:  7,
		Country: "",
	}
	AZ = Alpha2Code{
		Code:    "AZ",
		Status:  1,
		Country: "Azerbaijan",
	}
	BA = Alpha2Code{
		Code:    "BA",
		Status:  1,
		Country: "Bosnia and Herzegovina",
	}
	BB = Alpha2Code{
		Code:    "BB",
		Status:  1,
		Country: "Barbados",
	}
	BC = Alpha2Code{
		Code:    "BC",
		Status:  7,
		Country: "",
	}
	BD = Alpha2Code{
		Code:    "BD",
		Status:  1,
		Country: "Bangladesh",
	}
	BE = Alpha2Code{
		Code:    "BE",
		Status:  1,
		Country: "Belgium",
	}
	BF = Alpha2Code{
		Code:    "BF",
		Status:  1,
		Country: "Burkina Faso",
	}
	BG = Alpha2Code{
		Code:    "BG",
		Status:  1,
		Country: "Bulgaria",
	}
	BH = Alpha2Code{
		Code:    "BH",
		Status:  1,
		Country: "Bahrain",
	}
	BI = Alpha2Code{
		Code:    "BI",
		Status:  1,
		Country: "Burundi",
	}
	BJ = Alpha2Code{
		Code:    "BJ",
		Status:  1,
		Country: "Benin",
	}
	BK = Alpha2Code{
		Code:    "BK",
		Status:  7,
		Country: "",
	}
	BL = Alpha2Code{
		Code:    "BL",
		Status:  1,
		Country: "Saint Barthélemy",
	}
	BM = Alpha2Code{
		Code:    "BM",
		Status:  1,
		Country: "Bermuda",
	}
	BN = Alpha2Code{
		Code:    "BN",
		Status:  1,
		Country: "Brunei Darussalam",
	}
	BO = Alpha2Code{
		Code:    "BO",
		Status:  1,
		Country: "Bolivia (Plurinational State of)",
	}
	BP = Alpha2Code{
		Code:    "BP",
		Status:  7,
		Country: "",
	}
	BQ = Alpha2Code{
		Code:    "BQ",
		Status:  1,
		Country: "Bonaire, Sint Eustatius and Saba",
	}
	BR = Alpha2Code{
		Code:    "BR",
		Status:  1,
		Country: "Brazil",
	}
	BS = Alpha2Code{
		Code:    "BS",
		Status:  1,
		Country: "Bahamas (the)",
	}
	BT = Alpha2Code{
		Code:    "BT",
		Status:  1,
		Country: "Bhutan",
	}
	BU = Alpha2Code{
		Code:    "BU",
		Status:  4,
		Country: "Burma",
	}
	BV = Alpha2Code{
		Code:    "BV",
		Status:  1,
		Country: "Bouvet Island",
	}
	BW = Alpha2Code{
		Code:    "BW",
		Status:  1,
		Country: "Botswana",
	}
	BX = Alpha2Code{
		Code:    "BX",
		Status:  5,
		Country: "Benelux Trademarks and Designs Office",
	}
	BY = Alpha2Code{
		Code:    "BY",
		Status:  1,
		Country: "Belarus",
	}
	BZ = Alpha2Code{
		Code:    "BZ",
		Status:  1,
		Country: "Belize",
	}
	CA = Alpha2Code{
		Code:    "CA",
		Status:  1,
		Country: "Canada",
	}
	CB = Alpha2Code{
		Code:    "CB",
		Status:  7,
		Country: "",
	}
	CC = Alpha2Code{
		Code:    "CC",
		Status:  1,
		Country: "Cocos (Keeling) Islands (the)",
	}
	CD = Alpha2Code{
		Code:    "CD",
		Status:  1,
		Country: "Congo (the Democratic Republic of the)",
	}
	CE = Alpha2Code{
		Code:    "CE",
		Status:  7,
		Country: "",
	}
	CF = Alpha2Code{
		Code:    "CF",
		Status:  1,
		Country: "Central African Republic (the)",
	}
	CG = Alpha2Code{
		Code:    "CG",
		Status:  1,
		Country: "Congo (the)",
	}
	CH = Alpha2Code{
		Code:    "CH",
		Status:  1,
		Country: "Switzerland",
	}
	CI = Alpha2Code{
		Code:    "CI",
		Status:  1,
		Country: "Côte d'Ivoire",
	}
	CJ = Alpha2Code{
		Code:    "CJ",
		Status:  7,
		Country: "",
	}
	CK = Alpha2Code{
		Code:    "CK",
		Status:  1,
		Country: "Cook Islands (the)",
	}
	CL = Alpha2Code{
		Code:    "CL",
		Status:  1,
		Country: "Chile",
	}
	CM = Alpha2Code{
		Code:    "CM",
		Status:  1,
		Country: "Cameroon",
	}
	CN = Alpha2Code{
		Code:    "CN",
		Status:  1,
		Country: "China",
	}
	CO = Alpha2Code{
		Code:    "CO",
		Status:  1,
		Country: "Colombia",
	}
	CP = Alpha2Code{
		Code:    "CP",
		Status:  3,
		Country: "Clipperton Island",
	}
	CQ = Alpha2Code{
		Code:    "CQ",
		Status:  3,
		Country: "",
	}
	CR = Alpha2Code{
		Code:    "CR",
		Status:  1,
		Country: "Costa Rica",
	}
	CS = Alpha2Code{
		Code:    "CS",
		Status:  4,
		Country: "Serbia and Montenegro",
	}
	CT = Alpha2Code{
		Code:    "CT",
		Status:  5,
		Country: "Canton and Enderbury Islands",
	}
	CU = Alpha2Code{
		Code:    "CU",
		Status:  1,
		Country: "Cuba",
	}
	CV = Alpha2Code{
		Code:    "CV",
		Status:  1,
		Country: "Cabo Verde",
	}
	CW = Alpha2Code{
		Code:    "CW",
		Status:  1,
		Country: "Curaçao",
	}
	CX = Alpha2Code{
		Code:    "CX",
		Status:  1,
		Country: "Christmas Island",
	}
	CY = Alpha2Code{
		Code:    "CY",
		Status:  1,
		Country: "Cyprus",
	}
	CZ = Alpha2Code{
		Code:    "CZ",
		Status:  1,
		Country: "Czechia",
	}
	DA = Alpha2Code{
		Code:    "DA",
		Status:  7,
		Country: "",
	}
	DB = Alpha2Code{
		Code:    "DB",
		Status:  7,
		Country: "",
	}
	DC = Alpha2Code{
		Code:    "DC",
		Status:  7,
		Country: "",
	}
	DD = Alpha2Code{
		Code:    "DD",
		Status:  5,
		Country: "German Democratic Republic",
	}
	DE = Alpha2Code{
		Code:    "DE",
		Status:  1,
		Country: "Germany",
	}
	DF = Alpha2Code{
		Code:    "DF",
		Status:  7,
		Country: "",
	}
	DG = Alpha2Code{
		Code:    "DG",
		Status:  3,
		Country: "Diego Garcia",
	}
	DH = Alpha2Code{
		Code:    "DH",
		Status:  7,
		Country: "",
	}
	DI = Alpha2Code{
		Code:    "DI",
		Status:  7,
		Country: "",
	}
	DJ = Alpha2Code{
		Code:    "DJ",
		Status:  1,
		Country: "Djibouti",
	}
	DK = Alpha2Code{
		Code:    "DK",
		Status:  1,
		Country: "Denmark",
	}
	DL = Alpha2Code{
		Code:    "DL",
		Status:  7,
		Country: "",
	}
	DM = Alpha2Code{
		Code:    "DM",
		Status:  1,
		Country: "Dominica",
	}
	DN = Alpha2Code{
		Code:    "DN",
		Status:  7,
		Country: "",
	}
	DO = Alpha2Code{
		Code:    "DO",
		Status:  1,
		Country: "Dominican Republic (the)",
	}
	DP = Alpha2Code{
		Code:    "DP",
		Status:  7,
		Country: "",
	}
	DQ = Alpha2Code{
		Code:    "DQ",
		Status:  7,
		Country: "",
	}
	DR = Alpha2Code{
		Code:    "DR",
		Status:  7,
		Country: "",
	}
	DS = Alpha2Code{
		Code:    "DS",
		Status:  7,
		Country: "",
	}
	DT = Alpha2Code{
		Code:    "DT",
		Status:  7,
		Country: "",
	}
	DU = Alpha2Code{
		Code:    "DU",
		Status:  7,
		Country: "",
	}
	DV = Alpha2Code{
		Code:    "DV",
		Status:  7,
		Country: "",
	}
	DW = Alpha2Code{
		Code:    "DW",
		Status:  7,
		Country: "",
	}
	DX = Alpha2Code{
		Code:    "DX",
		Status:  7,
		Country: "",
	}
	DY = Alpha2Code{
		Code:    "DY",
		Status:  5,
		Country: "Benin",
	}
	DZ = Alpha2Code{
		Code:    "DZ",
		Status:  1,
		Country: "Algeria",
	}
	EA = Alpha2Code{
		Code:    "EA",
		Status:  3,
		Country: "Ceuta, Melilla",
	}
	EB = Alpha2Code{
		Code:    "EB",
		Status:  7,
		Country: "",
	}
	EC = Alpha2Code{
		Code:    "EC",
		Status:  1,
		Country: "Ecuador",
	}
	ED = Alpha2Code{
		Code:    "ED",
		Status:  7,
		Country: "",
	}
	EE = Alpha2Code{
		Code:    "EE",
		Status:  1,
		Country: "Estonia",
	}
	EF = Alpha2Code{
		Code:    "EF",
		Status:  5,
		Country: "Union of Countries under the European Community Patent Convention",
	}
	EG = Alpha2Code{
		Code:    "EG",
		Status:  1,
		Country: "Egypt",
	}
	EH = Alpha2Code{
		Code:    "EH",
		Status:  1,
		Country: "Western Sahara*",
	}
	EI = Alpha2Code{
		Code:    "EI",
		Status:  7,
		Country: "",
	}
	EJ = Alpha2Code{
		Code:    "EJ",
		Status:  7,
		Country: "",
	}
	EK = Alpha2Code{
		Code:    "EK",
		Status:  7,
		Country: "",
	}
	EL = Alpha2Code{
		Code:    "EL",
		Status:  7,
		Country: "",
	}
	EM = Alpha2Code{
		Code:    "EM",
		Status:  5,
		Country: "European Trademark Office",
	}
	EN = Alpha2Code{
		Code:    "EN",
		Status:  7,
		Country: "",
	}
	EO = Alpha2Code{
		Code:    "EO",
		Status:  7,
		Country: "",
	}
	EP = Alpha2Code{
		Code:    "EP",
		Status:  5,
		Country: "European Patent Organization",
	}
	EQ = Alpha2Code{
		Code:    "EQ",
		Status:  7,
		Country: "",
	}
	ER = Alpha2Code{
		Code:    "ER",
		Status:  1,
		Country: "Eritrea",
	}
	ES = Alpha2Code{
		Code:    "ES",
		Status:  1,
		Country: "Spain",
	}
	ET = Alpha2Code{
		Code:    "ET",
		Status:  1,
		Country: "Ethiopia",
	}
	EU = Alpha2Code{
		Code:    "EU",
		Status:  3,
		Country: "European Union",
	}
	EV = Alpha2Code{
		Code:    "EV",
		Status:  5,
		Country: "Eurasian Patent Organization",
	}
	EW = Alpha2Code{
		Code:    "EW",
		Status:  5,
		Country: "Estonia",
	}
	EX = Alpha2Code{
		Code:    "EX",
		Status:  7,
		Country: "",
	}
	EY = Alpha2Code{
		Code:    "EY",
		Status:  7,
		Country: "",
	}
	EZ = Alpha2Code{
		Code:    "EZ",
		Status:  3,
		Country: "",
	}
	FA = Alpha2Code{
		Code:    "FA",
		Status:  7,
		Country: "",
	}
	FB = Alpha2Code{
		Code:    "FB",
		Status:  7,
		Country: "",
	}
	FC = Alpha2Code{
		Code:    "FC",
		Status:  7,
		Country: "",
	}
	FD = Alpha2Code{
		Code:    "FD",
		Status:  7,
		Country: "",
	}
	FE = Alpha2Code{
		Code:    "FE",
		Status:  7,
		Country: "",
	}
	FF = Alpha2Code{
		Code:    "FF",
		Status:  7,
		Country: "",
	}
	FG = Alpha2Code{
		Code:    "FG",
		Status:  7,
		Country: "",
	}
	FH = Alpha2Code{
		Code:    "FH",
		Status:  7,
		Country: "",
	}
	FI = Alpha2Code{
		Code:    "FI",
		Status:  1,
		Country: "Finland",
	}
	FJ = Alpha2Code{
		Code:    "FJ",
		Status:  1,
		Country: "Fiji",
	}
	FK = Alpha2Code{
		Code:    "FK",
		Status:  1,
		Country: "Falkland Islands (the) [Malvinas]",
	}
	FL = Alpha2Code{
		Code:    "FL",
		Status:  5,
		Country: "Liechtenstein",
	}
	FM = Alpha2Code{
		Code:    "FM",
		Status:  1,
		Country: "Micronesia (Federated States of)",
	}
	FN = Alpha2Code{
		Code:    "FN",
		Status:  7,
		Country: "",
	}
	FO = Alpha2Code{
		Code:    "FO",
		Status:  1,
		Country: "Faroe Islands (the)",
	}
	FP = Alpha2Code{
		Code:    "FP",
		Status:  7,
		Country: "",
	}
	FQ = Alpha2Code{
		Code:    "FQ",
		Status:  5,
		Country: "French Southern and Antarctic Territories",
	}
	FR = Alpha2Code{
		Code:    "FR",
		Status:  1,
		Country: "France",
	}
	FS = Alpha2Code{
		Code:    "FS",
		Status:  7,
		Country: "",
	}
	FT = Alpha2Code{
		Code:    "FT",
		Status:  7,
		Country: "",
	}
	FU = Alpha2Code{
		Code:    "FU",
		Status:  7,
		Country: "",
	}
	FV = Alpha2Code{
		Code:    "FV",
		Status:  7,
		Country: "",
	}
	FW = Alpha2Code{
		Code:    "FW",
		Status:  7,
		Country: "",
	}
	FX = Alpha2Code{
		Code:    "FX",
		Status:  3,
		Country: "France, Metropolitan",
	}
	FY = Alpha2Code{
		Code:    "FY",
		Status:  7,
		Country: "",
	}
	FZ = Alpha2Code{
		Code:    "FZ",
		Status:  7,
		Country: "",
	}
	GA = Alpha2Code{
		Code:    "GA",
		Status:  1,
		Country: "Gabon",
	}
	GB = Alpha2Code{
		Code:    "GB",
		Status:  1,
		Country: "United Kingdom of Great Britain and Northern Ireland (the)",
	}
	GC = Alpha2Code{
		Code:    "GC",
		Status:  5,
		Country: "Patent Office of the Cooperation Council for the Arab States of the Gulf (GCC)",
	}
	GD = Alpha2Code{
		Code:    "GD",
		Status:  1,
		Country: "Grenada",
	}
	GE = Alpha2Code{
		Code:    "GE",
		Status:  1,
		Country: "Georgia",
	}
	GF = Alpha2Code{
		Code:    "GF",
		Status:  1,
		Country: "French Guiana",
	}
	GG = Alpha2Code{
		Code:    "GG",
		Status:  1,
		Country: "Guernsey",
	}
	GH = Alpha2Code{
		Code:    "GH",
		Status:  1,
		Country: "Ghana",
	}
	GI = Alpha2Code{
		Code:    "GI",
		Status:  1,
		Country: "Gibraltar",
	}
	GJ = Alpha2Code{
		Code:    "GJ",
		Status:  7,
		Country: "",
	}
	GK = Alpha2Code{
		Code:    "GK",
		Status:  7,
		Country: "",
	}
	GL = Alpha2Code{
		Code:    "GL",
		Status:  1,
		Country: "Greenland",
	}
	GM = Alpha2Code{
		Code:    "GM",
		Status:  1,
		Country: "Gambia (the)",
	}
	GN = Alpha2Code{
		Code:    "GN",
		Status:  1,
		Country: "Guinea",
	}
	GO = Alpha2Code{
		Code:    "GO",
		Status:  7,
		Country: "",
	}
	GP = Alpha2Code{
		Code:    "GP",
		Status:  1,
		Country: "Guadeloupe",
	}
	GQ = Alpha2Code{
		Code:    "GQ",
		Status:  1,
		Country: "Equatorial Guinea",
	}
	GR = Alpha2Code{
		Code:    "GR",
		Status:  1,
		Country: "Greece",
	}
	GS = Alpha2Code{
		Code:    "GS",
		Status:  1,
		Country: "South Georgia and the South Sandwich Islands",
	}
	GT = Alpha2Code{
		Code:    "GT",
		Status:  1,
		Country: "Guatemala",
	}
	GU = Alpha2Code{
		Code:    "GU",
		Status:  1,
		Country: "Guam",
	}
	GV = Alpha2Code{
		Code:    "GV",
		Status:  7,
		Country: "",
	}
	GW = Alpha2Code{
		Code:    "GW",
		Status:  1,
		Country: "Guinea-Bissau",
	}
	GX = Alpha2Code{
		Code:    "GX",
		Status:  7,
		Country: "",
	}
	GY = Alpha2Code{
		Code:    "GY",
		Status:  1,
		Country: "Guyana",
	}
	GZ = Alpha2Code{
		Code:    "GZ",
		Status:  7,
		Country: "",
	}
	HA = Alpha2Code{
		Code:    "HA",
		Status:  7,
		Country: "",
	}
	HB = Alpha2Code{
		Code:    "HB",
		Status:  7,
		Country: "",
	}
	HC = Alpha2Code{
		Code:    "HC",
		Status:  7,
		Country: "",
	}
	HD = Alpha2Code{
		Code:    "HD",
		Status:  7,
		Country: "",
	}
	HE = Alpha2Code{
		Code:    "HE",
		Status:  7,
		Country: "",
	}
	HF = Alpha2Code{
		Code:    "HF",
		Status:  7,
		Country: "",
	}
	HG = Alpha2Code{
		Code:    "HG",
		Status:  7,
		Country: "",
	}
	HH = Alpha2Code{
		Code:    "HH",
		Status:  7,
		Country: "",
	}
	HI = Alpha2Code{
		Code:    "HI",
		Status:  7,
		Country: "",
	}
	HJ = Alpha2Code{
		Code:    "HJ",
		Status:  7,
		Country: "",
	}
	HK = Alpha2Code{
		Code:    "HK",
		Status:  1,
		Country: "Hong Kong",
	}
	HL = Alpha2Code{
		Code:    "HL",
		Status:  7,
		Country: "",
	}
	HM = Alpha2Code{
		Code:    "HM",
		Status:  1,
		Country: "Heard Island and McDonald Islands",
	}
	HN = Alpha2Code{
		Code:    "HN",
		Status:  1,
		Country: "Honduras",
	}
	HO = Alpha2Code{
		Code:    "HO",
		Status:  7,
		Country: "",
	}
	HP = Alpha2Code{
		Code:    "HP",
		Status:  7,
		Country: "",
	}
	HQ = Alpha2Code{
		Code:    "HQ",
		Status:  7,
		Country: "",
	}
	HR = Alpha2Code{
		Code:    "HR",
		Status:  1,
		Country: "Croatia",
	}
	HS = Alpha2Code{
		Code:    "HS",
		Status:  7,
		Country: "",
	}
	HT = Alpha2Code{
		Code:    "HT",
		Status:  1,
		Country: "Haiti",
	}
	HU = Alpha2Code{
		Code:    "HU",
		Status:  1,
		Country: "Hungary",
	}
	HV = Alpha2Code{
		Code:    "HV",
		Status:  5,
		Country: "Upper Volta",
	}
	HW = Alpha2Code{
		Code:    "HW",
		Status:  7,
		Country: "",
	}
	HX = Alpha2Code{
		Code:    "HX",
		Status:  7,
		Country: "",
	}
	HY = Alpha2Code{
		Code:    "HY",
		Status:  7,
		Country: "",
	}
	HZ = Alpha2Code{
		Code:    "HZ",
		Status:  7,
		Country: "",
	}
	IA = Alpha2Code{
		Code:    "IA",
		Status:  7,
		Country: "",
	}
	IB = Alpha2Code{
		Code:    "IB",
		Status:  5,
		Country: "International Bureau of WIPO",
	}
	IC = Alpha2Code{
		Code:    "IC",
		Status:  3,
		Country: "Canary Islands",
	}
	ID = Alpha2Code{
		Code:    "ID",
		Status:  1,
		Country: "Indonesia",
	}
	IE = Alpha2Code{
		Code:    "IE",
		Status:  1,
		Country: "Ireland",
	}
	IF = Alpha2Code{
		Code:    "IF",
		Status:  7,
		Country: "",
	}
	IG = Alpha2Code{
		Code:    "IG",
		Status:  7,
		Country: "",
	}
	IH = Alpha2Code{
		Code:    "IH",
		Status:  7,
		Country: "",
	}
	II = Alpha2Code{
		Code:    "II",
		Status:  7,
		Country: "",
	}
	IJ = Alpha2Code{
		Code:    "IJ",
		Status:  7,
		Country: "",
	}
	IK = Alpha2Code{
		Code:    "IK",
		Status:  7,
		Country: "",
	}
	IL = Alpha2Code{
		Code:    "IL",
		Status:  1,
		Country: "Israel",
	}
	IM = Alpha2Code{
		Code:    "IM",
		Status:  1,
		Country: "Isle of Man",
	}
	IN = Alpha2Code{
		Code:    "IN",
		Status:  1,
		Country: "India",
	}
	IO = Alpha2Code{
		Code:    "IO",
		Status:  1,
		Country: "British Indian Ocean Territory (the)",
	}
	IP = Alpha2Code{
		Code:    "IP",
		Status:  7,
		Country: "",
	}
	IQ = Alpha2Code{
		Code:    "IQ",
		Status:  1,
		Country: "Iraq",
	}
	IR = Alpha2Code{
		Code:    "IR",
		Status:  1,
		Country: "Iran (Islamic Republic of)",
	}
	IS = Alpha2Code{
		Code:    "IS",
		Status:  1,
		Country: "Iceland",
	}
	IT = Alpha2Code{
		Code:    "IT",
		Status:  1,
		Country: "Italy",
	}
	IU = Alpha2Code{
		Code:    "IU",
		Status:  7,
		Country: "",
	}
	IV = Alpha2Code{
		Code:    "IV",
		Status:  7,
		Country: "",
	}
	IW = Alpha2Code{
		Code:    "IW",
		Status:  7,
		Country: "",
	}
	IX = Alpha2Code{
		Code:    "IX",
		Status:  7,
		Country: "",
	}
	IY = Alpha2Code{
		Code:    "IY",
		Status:  7,
		Country: "",
	}
	IZ = Alpha2Code{
		Code:    "IZ",
		Status:  7,
		Country: "",
	}
	JA = Alpha2Code{
		Code:    "JA",
		Status:  5,
		Country: "Jamaica",
	}
	JB = Alpha2Code{
		Code:    "JB",
		Status:  7,
		Country: "",
	}
	JC = Alpha2Code{
		Code:    "JC",
		Status:  7,
		Country: "",
	}
	JD = Alpha2Code{
		Code:    "JD",
		Status:  7,
		Country: "",
	}
	JE = Alpha2Code{
		Code:    "JE",
		Status:  1,
		Country: "Jersey",
	}
	JF = Alpha2Code{
		Code:    "JF",
		Status:  7,
		Country: "",
	}
	JG = Alpha2Code{
		Code:    "JG",
		Status:  7,
		Country: "",
	}
	JH = Alpha2Code{
		Code:    "JH",
		Status:  7,
		Country: "",
	}
	JI = Alpha2Code{
		Code:    "JI",
		Status:  7,
		Country: "",
	}
	JJ = Alpha2Code{
		Code:    "JJ",
		Status:  7,
		Country: "",
	}
	JK = Alpha2Code{
		Code:    "JK",
		Status:  7,
		Country: "",
	}
	JL = Alpha2Code{
		Code:    "JL",
		Status:  7,
		Country: "",
	}
	JM = Alpha2Code{
		Code:    "JM",
		Status:  1,
		Country: "Jamaica",
	}
	JN = Alpha2Code{
		Code:    "JN",
		Status:  7,
		Country: "",
	}
	JO = Alpha2Code{
		Code:    "JO",
		Status:  1,
		Country: "Jordan",
	}
	JP = Alpha2Code{
		Code:    "JP",
		Status:  1,
		Country: "Japan",
	}
	JQ = Alpha2Code{
		Code:    "JQ",
		Status:  7,
		Country: "",
	}
	JR = Alpha2Code{
		Code:    "JR",
		Status:  7,
		Country: "",
	}
	JS = Alpha2Code{
		Code:    "JS",
		Status:  7,
		Country: "",
	}
	JT = Alpha2Code{
		Code:    "JT",
		Status:  5,
		Country: "Johnston Island",
	}
	JU = Alpha2Code{
		Code:    "JU",
		Status:  7,
		Country: "",
	}
	JV = Alpha2Code{
		Code:    "JV",
		Status:  7,
		Country: "",
	}
	JW = Alpha2Code{
		Code:    "JW",
		Status:  7,
		Country: "",
	}
	JX = Alpha2Code{
		Code:    "JX",
		Status:  7,
		Country: "",
	}
	JY = Alpha2Code{
		Code:    "JY",
		Status:  7,
		Country: "",
	}
	JZ = Alpha2Code{
		Code:    "JZ",
		Status:  7,
		Country: "",
	}
	KA = Alpha2Code{
		Code:    "KA",
		Status:  7,
		Country: "",
	}
	KB = Alpha2Code{
		Code:    "KB",
		Status:  7,
		Country: "",
	}
	KC = Alpha2Code{
		Code:    "KC",
		Status:  7,
		Country: "",
	}
	KD = Alpha2Code{
		Code:    "KD",
		Status:  7,
		Country: "",
	}
	KE = Alpha2Code{
		Code:    "KE",
		Status:  1,
		Country: "Kenya",
	}
	KF = Alpha2Code{
		Code:    "KF",
		Status:  7,
		Country: "",
	}
	KG = Alpha2Code{
		Code:    "KG",
		Status:  1,
		Country: "Kyrgyzstan",
	}
	KH = Alpha2Code{
		Code:    "KH",
		Status:  1,
		Country: "Cambodia",
	}
	KI = Alpha2Code{
		Code:    "KI",
		Status:  1,
		Country: "Kiribati",
	}
	KJ = Alpha2Code{
		Code:    "KJ",
		Status:  7,
		Country: "",
	}
	KK = Alpha2Code{
		Code:    "KK",
		Status:  7,
		Country: "",
	}
	KL = Alpha2Code{
		Code:    "KL",
		Status:  7,
		Country: "",
	}
	KM = Alpha2Code{
		Code:    "KM",
		Status:  1,
		Country: "Comoros (the)",
	}
	KN = Alpha2Code{
		Code:    "KN",
		Status:  1,
		Country: "Saint Kitts and Nevis",
	}
	KO = Alpha2Code{
		Code:    "KO",
		Status:  7,
		Country: "",
	}
	KP = Alpha2Code{
		Code:    "KP",
		Status:  1,
		Country: "Korea (the Democratic People's Republic of)",
	}
	KQ = Alpha2Code{
		Code:    "KQ",
		Status:  7,
		Country: "",
	}
	KR = Alpha2Code{
		Code:    "KR",
		Status:  1,
		Country: "Korea (the Republic of)",
	}
	KS = Alpha2Code{
		Code:    "KS",
		Status:  7,
		Country: "",
	}
	KT = Alpha2Code{
		Code:    "KT",
		Status:  7,
		Country: "",
	}
	KU = Alpha2Code{
		Code:    "KU",
		Status:  7,
		Country: "",
	}
	KV = Alpha2Code{
		Code:    "KV",
		Status:  7,
		Country: "",
	}
	KW = Alpha2Code{
		Code:    "KW",
		Status:  1,
		Country: "Kuwait",
	}
	KX = Alpha2Code{
		Code:    "KX",
		Status:  7,
		Country: "",
	}
	KY = Alpha2Code{
		Code:    "KY",
		Status:  1,
		Country: "Cayman Islands (the)",
	}
	KZ = Alpha2Code{
		Code:    "KZ",
		Status:  1,
		Country: "Kazakhstan",
	}
	LA = Alpha2Code{
		Code:    "LA",
		Status:  1,
		Country: "Lao People's Democratic Republic (the)",
	}
	LB = Alpha2Code{
		Code:    "LB",
		Status:  1,
		Country: "Lebanon",
	}
	LC = Alpha2Code{
		Code:    "LC",
		Status:  1,
		Country: "Saint Lucia",
	}
	LD = Alpha2Code{
		Code:    "LD",
		Status:  7,
		Country: "",
	}
	LE = Alpha2Code{
		Code:    "LE",
		Status:  7,
		Country: "",
	}
	LF = Alpha2Code{
		Code:    "LF",
		Status:  5,
		Country: "Libya Fezzan",
	}
	LG = Alpha2Code{
		Code:    "LG",
		Status:  7,
		Country: "",
	}
	LH = Alpha2Code{
		Code:    "LH",
		Status:  7,
		Country: "",
	}
	LI = Alpha2Code{
		Code:    "LI",
		Status:  1,
		Country: "Liechtenstein",
	}
	LJ = Alpha2Code{
		Code:    "LJ",
		Status:  7,
		Country: "",
	}
	LK = Alpha2Code{
		Code:    "LK",
		Status:  1,
		Country: "Sri Lanka",
	}
	LL = Alpha2Code{
		Code:    "LL",
		Status:  7,
		Country: "",
	}
	LM = Alpha2Code{
		Code:    "LM",
		Status:  7,
		Country: "",
	}
	LN = Alpha2Code{
		Code:    "LN",
		Status:  7,
		Country: "",
	}
	LO = Alpha2Code{
		Code:    "LO",
		Status:  7,
		Country: "",
	}
	LP = Alpha2Code{
		Code:    "LP",
		Status:  7,
		Country: "",
	}
	LQ = Alpha2Code{
		Code:    "LQ",
		Status:  7,
		Country: "",
	}
	LR = Alpha2Code{
		Code:    "LR",
		Status:  1,
		Country: "Liberia",
	}
	LS = Alpha2Code{
		Code:    "LS",
		Status:  1,
		Country: "Lesotho",
	}
	LT = Alpha2Code{
		Code:    "LT",
		Status:  1,
		Country: "Lithuania",
	}
	LU = Alpha2Code{
		Code:    "LU",
		Status:  1,
		Country: "Luxembourg",
	}
	LV = Alpha2Code{
		Code:    "LV",
		Status:  1,
		Country: "Latvia",
	}
	LW = Alpha2Code{
		Code:    "LW",
		Status:  7,
		Country: "",
	}
	LX = Alpha2Code{
		Code:    "LX",
		Status:  7,
		Country: "",
	}
	LY = Alpha2Code{
		Code:    "LY",
		Status:  1,
		Country: "Libya",
	}
	LZ = Alpha2Code{
		Code:    "LZ",
		Status:  7,
		Country: "",
	}
	MA = Alpha2Code{
		Code:    "MA",
		Status:  1,
		Country: "Morocco",
	}
	MB = Alpha2Code{
		Code:    "MB",
		Status:  7,
		Country: "",
	}
	MC = Alpha2Code{
		Code:    "MC",
		Status:  1,
		Country: "Monaco",
	}
	MD = Alpha2Code{
		Code:    "MD",
		Status:  1,
		Country: "Moldova (the Republic of)",
	}
	ME = Alpha2Code{
		Code:    "ME",
		Status:  1,
		Country: "Montenegro",
	}
	MF = Alpha2Code{
		Code:    "MF",
		Status:  1,
		Country: "Saint Martin (French part)",
	}
	MG = Alpha2Code{
		Code:    "MG",
		Status:  1,
		Country: "Madagascar",
	}
	MH = Alpha2Code{
		Code:    "MH",
		Status:  1,
		Country: "Marshall Islands (the)",
	}
	MI = Alpha2Code{
		Code:    "MI",
		Status:  5,
		Country: "Midway Islands",
	}
	MJ = Alpha2Code{
		Code:    "MJ",
		Status:  7,
		Country: "",
	}
	MK = Alpha2Code{
		Code:    "MK",
		Status:  1,
		Country: "North Macedonia",
	}
	ML = Alpha2Code{
		Code:    "ML",
		Status:  1,
		Country: "Mali",
	}
	MM = Alpha2Code{
		Code:    "MM",
		Status:  1,
		Country: "Myanmar",
	}
	MN = Alpha2Code{
		Code:    "MN",
		Status:  1,
		Country: "Mongolia",
	}
	MO = Alpha2Code{
		Code:    "MO",
		Status:  1,
		Country: "Macao",
	}
	MP = Alpha2Code{
		Code:    "MP",
		Status:  1,
		Country: "Northern Mariana Islands (the)",
	}
	MQ = Alpha2Code{
		Code:    "MQ",
		Status:  1,
		Country: "Martinique",
	}
	MR = Alpha2Code{
		Code:    "MR",
		Status:  1,
		Country: "Mauritania",
	}
	MS = Alpha2Code{
		Code:    "MS",
		Status:  1,
		Country: "Montserrat",
	}
	MT = Alpha2Code{
		Code:    "MT",
		Status:  1,
		Country: "Malta",
	}
	MU = Alpha2Code{
		Code:    "MU",
		Status:  1,
		Country: "Mauritius",
	}
	MV = Alpha2Code{
		Code:    "MV",
		Status:  1,
		Country: "Maldives",
	}
	MW = Alpha2Code{
		Code:    "MW",
		Status:  1,
		Country: "Malawi",
	}
	MX = Alpha2Code{
		Code:    "MX",
		Status:  1,
		Country: "Mexico",
	}
	MY = Alpha2Code{
		Code:    "MY",
		Status:  1,
		Country: "Malaysia",
	}
	MZ = Alpha2Code{
		Code:    "MZ",
		Status:  1,
		Country: "Mozambique",
	}
	NA = Alpha2Code{
		Code:    "NA",
		Status:  1,
		Country: "Namibia",
	}
	NB = Alpha2Code{
		Code:    "NB",
		Status:  7,
		Country: "",
	}
	NC = Alpha2Code{
		Code:    "NC",
		Status:  1,
		Country: "New Caledonia",
	}
	ND = Alpha2Code{
		Code:    "ND",
		Status:  7,
		Country: "",
	}
	NE = Alpha2Code{
		Code:    "NE",
		Status:  1,
		Country: "Niger (the)",
	}
	NF = Alpha2Code{
		Code:    "NF",
		Status:  1,
		Country: "Norfolk Island",
	}
	NG = Alpha2Code{
		Code:    "NG",
		Status:  1,
		Country: "Nigeria",
	}
	NH = Alpha2Code{
		Code:    "NH",
		Status:  5,
		Country: "New Hebrides",
	}
	NI = Alpha2Code{
		Code:    "NI",
		Status:  1,
		Country: "Nicaragua",
	}
	NJ = Alpha2Code{
		Code:    "NJ",
		Status:  7,
		Country: "",
	}
	NK = Alpha2Code{
		Code:    "NK",
		Status:  7,
		Country: "",
	}
	NL = Alpha2Code{
		Code:    "NL",
		Status:  1,
		Country: "Netherlands (the)",
	}
	NM = Alpha2Code{
		Code:    "NM",
		Status:  7,
		Country: "",
	}
	NN = Alpha2Code{
		Code:    "NN",
		Status:  7,
		Country: "",
	}
	NO = Alpha2Code{
		Code:    "NO",
		Status:  1,
		Country: "Norway",
	}
	NP = Alpha2Code{
		Code:    "NP",
		Status:  1,
		Country: "Nepal",
	}
	NQ = Alpha2Code{
		Code:    "NQ",
		Status:  5,
		Country: "Dronning Maud Land",
	}
	NR = Alpha2Code{
		Code:    "NR",
		Status:  1,
		Country: "Nauru",
	}
	NS = Alpha2Code{
		Code:    "NS",
		Status:  7,
		Country: "",
	}
	NT = Alpha2Code{
		Code:    "NT",
		Status:  4,
		Country: "Neutral Zone",
	}
	NU = Alpha2Code{
		Code:    "NU",
		Status:  1,
		Country: "Niue",
	}
	NV = Alpha2Code{
		Code:    "NV",
		Status:  7,
		Country: "",
	}
	NW = Alpha2Code{
		Code:    "NW",
		Status:  7,
		Country: "",
	}
	NX = Alpha2Code{
		Code:    "NX",
		Status:  7,
		Country: "",
	}
	NY = Alpha2Code{
		Code:    "NY",
		Status:  7,
		Country: "",
	}
	NZ = Alpha2Code{
		Code:    "NZ",
		Status:  1,
		Country: "New Zealand",
	}
	OA = Alpha2Code{
		Code:    "OA",
		Status:  5,
		Country: "African Intellectual Property Organization",
	}
	OB = Alpha2Code{
		Code:    "OB",
		Status:  7,
		Country: "",
	}
	OC = Alpha2Code{
		Code:    "OC",
		Status:  7,
		Country: "",
	}
	OD = Alpha2Code{
		Code:    "OD",
		Status:  7,
		Country: "",
	}
	OE = Alpha2Code{
		Code:    "OE",
		Status:  7,
		Country: "",
	}
	OF = Alpha2Code{
		Code:    "OF",
		Status:  7,
		Country: "",
	}
	OG = Alpha2Code{
		Code:    "OG",
		Status:  7,
		Country: "",
	}
	OH = Alpha2Code{
		Code:    "OH",
		Status:  7,
		Country: "",
	}
	OI = Alpha2Code{
		Code:    "OI",
		Status:  7,
		Country: "",
	}
	OJ = Alpha2Code{
		Code:    "OJ",
		Status:  7,
		Country: "",
	}
	OK = Alpha2Code{
		Code:    "OK",
		Status:  7,
		Country: "",
	}
	OL = Alpha2Code{
		Code:    "OL",
		Status:  7,
		Country: "",
	}
	OM = Alpha2Code{
		Code:    "OM",
		Status:  1,
		Country: "Oman",
	}
	ON = Alpha2Code{
		Code:    "ON",
		Status:  7,
		Country: "",
	}
	OO = Alpha2Code{
		Code:    "OO",
		Status:  7,
		Country: "",
	}
	OP = Alpha2Code{
		Code:    "OP",
		Status:  7,
		Country: "",
	}
	OQ = Alpha2Code{
		Code:    "OQ",
		Status:  7,
		Country: "",
	}
	OR = Alpha2Code{
		Code:    "OR",
		Status:  7,
		Country: "",
	}
	OS = Alpha2Code{
		Code:    "OS",
		Status:  7,
		Country: "",
	}
	OT = Alpha2Code{
		Code:    "OT",
		Status:  7,
		Country: "",
	}
	OU = Alpha2Code{
		Code:    "OU",
		Status:  7,
		Country: "",
	}
	OV = Alpha2Code{
		Code:    "OV",
		Status:  7,
		Country: "",
	}
	OW = Alpha2Code{
		Code:    "OW",
		Status:  7,
		Country: "",
	}
	OX = Alpha2Code{
		Code:    "OX",
		Status:  7,
		Country: "",
	}
	OY = Alpha2Code{
		Code:    "OY",
		Status:  7,
		Country: "",
	}
	OZ = Alpha2Code{
		Code:    "OZ",
		Status:  7,
		Country: "",
	}
	PA = Alpha2Code{
		Code:    "PA",
		Status:  1,
		Country: "Panama",
	}
	PB = Alpha2Code{
		Code:    "PB",
		Status:  7,
		Country: "",
	}
	PC = Alpha2Code{
		Code:    "PC",
		Status:  5,
		Country: "Pacific Islands (Trust Territory)",
	}
	PD = Alpha2Code{
		Code:    "PD",
		Status:  7,
		Country: "",
	}
	PE = Alpha2Code{
		Code:    "PE",
		Status:  1,
		Country: "Peru",
	}
	PF = Alpha2Code{
		Code:    "PF",
		Status:  1,
		Country: "French Polynesia",
	}
	PG = Alpha2Code{
		Code:    "PG",
		Status:  1,
		Country: "Papua New Guinea",
	}
	PH = Alpha2Code{
		Code:    "PH",
		Status:  1,
		Country: "Philippines (the)",
	}
	PI = Alpha2Code{
		Code:    "PI",
		Status:  5,
		Country: "Philippines",
	}
	PJ = Alpha2Code{
		Code:    "PJ",
		Status:  7,
		Country: "",
	}
	PK = Alpha2Code{
		Code:    "PK",
		Status:  1,
		Country: "Pakistan",
	}
	PL = Alpha2Code{
		Code:    "PL",
		Status:  1,
		Country: "Poland",
	}
	PM = Alpha2Code{
		Code:    "PM",
		Status:  1,
		Country: "Saint Pierre and Miquelon",
	}
	PN = Alpha2Code{
		Code:    "PN",
		Status:  1,
		Country: "Pitcairn",
	}
	PO = Alpha2Code{
		Code:    "PO",
		Status:  7,
		Country: "",
	}
	PP = Alpha2Code{
		Code:    "PP",
		Status:  7,
		Country: "",
	}
	PQ = Alpha2Code{
		Code:    "PQ",
		Status:  7,
		Country: "",
	}
	PR = Alpha2Code{
		Code:    "PR",
		Status:  1,
		Country: "Puerto Rico",
	}
	PS = Alpha2Code{
		Code:    "PS",
		Status:  1,
		Country: "Palestine, State of",
	}
	PT = Alpha2Code{
		Code:    "PT",
		Status:  1,
		Country: "Portugal",
	}
	PU = Alpha2Code{
		Code:    "PU",
		Status:  5,
		Country: "United States Miscellaneous Pacific Islands",
	}
	PV = Alpha2Code{
		Code:    "PV",
		Status:  7,
		Country: "",
	}
	PW = Alpha2Code{
		Code:    "PW",
		Status:  1,
		Country: "Palau",
	}
	PX = Alpha2Code{
		Code:    "PX",
		Status:  7,
		Country: "",
	}
	PY = Alpha2Code{
		Code:    "PY",
		Status:  1,
		Country: "Paraguay",
	}
	PZ = Alpha2Code{
		Code:    "PZ",
		Status:  5,
		Country: "Panama Canal Zone",
	}
	QA = Alpha2Code{
		Code:    "QA",
		Status:  1,
		Country: "Qatar",
	}
	QB = Alpha2Code{
		Code:    "QB",
		Status:  7,
		Country: "",
	}
	QC = Alpha2Code{
		Code:    "QC",
		Status:  7,
		Country: "",
	}
	QD = Alpha2Code{
		Code:    "QD",
		Status:  7,
		Country: "",
	}
	QE = Alpha2Code{
		Code:    "QE",
		Status:  7,
		Country: "",
	}
	QF = Alpha2Code{
		Code:    "QF",
		Status:  7,
		Country: "",
	}
	QG = Alpha2Code{
		Code:    "QG",
		Status:  7,
		Country: "",
	}
	QH = Alpha2Code{
		Code:    "QH",
		Status:  7,
		Country: "",
	}
	QI = Alpha2Code{
		Code:    "QI",
		Status:  7,
		Country: "",
	}
	QJ = Alpha2Code{
		Code:    "QJ",
		Status:  7,
		Country: "",
	}
	QK = Alpha2Code{
		Code:    "QK",
		Status:  7,
		Country: "",
	}
	QL = Alpha2Code{
		Code:    "QL",
		Status:  7,
		Country: "",
	}
	QM = Alpha2Code{
		Code:    "QM",
		Status:  2,
		Country: "",
	}
	QN = Alpha2Code{
		Code:    "QN",
		Status:  2,
		Country: "",
	}
	QO = Alpha2Code{
		Code:    "QO",
		Status:  2,
		Country: "",
	}
	QP = Alpha2Code{
		Code:    "QP",
		Status:  2,
		Country: "",
	}
	QQ = Alpha2Code{
		Code:    "QQ",
		Status:  2,
		Country: "",
	}
	QR = Alpha2Code{
		Code:    "QR",
		Status:  2,
		Country: "",
	}
	QS = Alpha2Code{
		Code:    "QS",
		Status:  2,
		Country: "",
	}
	QT = Alpha2Code{
		Code:    "QT",
		Status:  2,
		Country: "",
	}
	QU = Alpha2Code{
		Code:    "QU",
		Status:  2,
		Country: "",
	}
	QV = Alpha2Code{
		Code:    "QV",
		Status:  2,
		Country: "",
	}
	QW = Alpha2Code{
		Code:    "QW",
		Status:  2,
		Country: "",
	}
	QX = Alpha2Code{
		Code:    "QX",
		Status:  2,
		Country: "",
	}
	QY = Alpha2Code{
		Code:    "QY",
		Status:  2,
		Country: "",
	}
	QZ = Alpha2Code{
		Code:    "QZ",
		Status:  2,
		Country: "",
	}
	RA = Alpha2Code{
		Code:    "RA",
		Status:  5,
		Country: "Argentina",
	}
	RB = Alpha2Code{
		Code:    "RB",
		Status:  5,
		Country: "Bolivia [cf. Botswana: identical code element]",
	}
	RC = Alpha2Code{
		Code:    "RC",
		Status:  5,
		Country: "China",
	}
	RD = Alpha2Code{
		Code:    "RD",
		Status:  7,
		Country: "",
	}
	RE = Alpha2Code{
		Code:    "RE",
		Status:  1,
		Country: "Réunion",
	}
	RF = Alpha2Code{
		Code:    "RF",
		Status:  7,
		Country: "",
	}
	RG = Alpha2Code{
		Code:    "RG",
		Status:  7,
		Country: "",
	}
	RH = Alpha2Code{
		Code:    "RH",
		Status:  5,
		Country: "Haiti",
	}
	RI = Alpha2Code{
		Code:    "RI",
		Status:  5,
		Country: "Indonesia",
	}
	RJ = Alpha2Code{
		Code:    "RJ",
		Status:  7,
		Country: "",
	}
	RK = Alpha2Code{
		Code:    "RK",
		Status:  7,
		Country: "",
	}
	RL = Alpha2Code{
		Code:    "RL",
		Status:  5,
		Country: "Lebanon",
	}
	RM = Alpha2Code{
		Code:    "RM",
		Status:  5,
		Country: "Madagascar",
	}
	RN = Alpha2Code{
		Code:    "RN",
		Status:  5,
		Country: "Niger",
	}
	RO = Alpha2Code{
		Code:    "RO",
		Status:  1,
		Country: "Romania",
	}
	RP = Alpha2Code{
		Code:    "RP",
		Status:  5,
		Country: "Philippines",
	}
	RQ = Alpha2Code{
		Code:    "RQ",
		Status:  7,
		Country: "",
	}
	RR = Alpha2Code{
		Code:    "RR",
		Status:  7,
		Country: "",
	}
	RS = Alpha2Code{
		Code:    "RS",
		Status:  1,
		Country: "Serbia",
	}
	RT = Alpha2Code{
		Code:    "RT",
		Status:  7,
		Country: "",
	}
	RU = Alpha2Code{
		Code:    "RU",
		Status:  1,
		Country: "Russian Federation (the)",
	}
	RV = Alpha2Code{
		Code:    "RV",
		Status:  7,
		Country: "",
	}
	RW = Alpha2Code{
		Code:    "RW",
		Status:  1,
		Country: "Rwanda",
	}
	RX = Alpha2Code{
		Code:    "RX",
		Status:  7,
		Country: "",
	}
	RY = Alpha2Code{
		Code:    "RY",
		Status:  7,
		Country: "",
	}
	RZ = Alpha2Code{
		Code:    "RZ",
		Status:  7,
		Country: "",
	}
	SA = Alpha2Code{
		Code:    "SA",
		Status:  1,
		Country: "Saudi Arabia",
	}
	SB = Alpha2Code{
		Code:    "SB",
		Status:  1,
		Country: "Solomon Islands",
	}
	SC = Alpha2Code{
		Code:    "SC",
		Status:  1,
		Country: "Seychelles",
	}
	SD = Alpha2Code{
		Code:    "SD",
		Status:  1,
		Country: "Sudan (the)",
	}
	SE = Alpha2Code{
		Code:    "SE",
		Status:  1,
		Country: "Sweden",
	}
	SF = Alpha2Code{
		Code:    "SF",
		Status:  5,
		Country: "Finland",
	}
	SG = Alpha2Code{
		Code:    "SG",
		Status:  1,
		Country: "Singapore",
	}
	SH = Alpha2Code{
		Code:    "SH",
		Status:  1,
		Country: "Saint Helena, Ascension and Tristan da Cunha",
	}
	SI = Alpha2Code{
		Code:    "SI",
		Status:  1,
		Country: "Slovenia",
	}
	SJ = Alpha2Code{
		Code:    "SJ",
		Status:  1,
		Country: "Svalbard and Jan Mayen",
	}
	SK = Alpha2Code{
		Code:    "SK",
		Status:  1,
		Country: "Slovakia",
	}
	SL = Alpha2Code{
		Code:    "SL",
		Status:  1,
		Country: "Sierra Leone",
	}
	SM = Alpha2Code{
		Code:    "SM",
		Status:  1,
		Country: "San Marino",
	}
	SN = Alpha2Code{
		Code:    "SN",
		Status:  1,
		Country: "Senegal",
	}
	SO = Alpha2Code{
		Code:    "SO",
		Status:  1,
		Country: "Somalia",
	}
	SP = Alpha2Code{
		Code:    "SP",
		Status:  7,
		Country: "",
	}
	SQ = Alpha2Code{
		Code:    "SQ",
		Status:  7,
		Country: "",
	}
	SR = Alpha2Code{
		Code:    "SR",
		Status:  1,
		Country: "Suriname",
	}
	SS = Alpha2Code{
		Code:    "SS",
		Status:  1,
		Country: "South Sudan",
	}
	ST = Alpha2Code{
		Code:    "ST",
		Status:  1,
		Country: "Sao Tome and Principe",
	}
	SU = Alpha2Code{
		Code:    "SU",
		Status:  3,
		Country: "USSR",
	}
	SV = Alpha2Code{
		Code:    "SV",
		Status:  1,
		Country: "El Salvador",
	}
	SW = Alpha2Code{
		Code:    "SW",
		Status:  7,
		Country: "",
	}
	SX = Alpha2Code{
		Code:    "SX",
		Status:  1,
		Country: "Sint Maarten (Dutch part)",
	}
	SY = Alpha2Code{
		Code:    "SY",
		Status:  1,
		Country: "Syrian Arab Republic (the)",
	}
	SZ = Alpha2Code{
		Code:    "SZ",
		Status:  1,
		Country: "Eswatini",
	}
	TA = Alpha2Code{
		Code:    "TA",
		Status:  3,
		Country: "Tristan da Cunha",
	}
	TB = Alpha2Code{
		Code:    "TB",
		Status:  7,
		Country: "",
	}
	TC = Alpha2Code{
		Code:    "TC",
		Status:  1,
		Country: "Turks and Caicos Islands (the)",
	}
	TD = Alpha2Code{
		Code:    "TD",
		Status:  1,
		Country: "Chad",
	}
	TE = Alpha2Code{
		Code:    "TE",
		Status:  7,
		Country: "",
	}
	TF = Alpha2Code{
		Code:    "TF",
		Status:  1,
		Country: "French Southern Territories (the)",
	}
	TG = Alpha2Code{
		Code:    "TG",
		Status:  1,
		Country: "Togo",
	}
	TH = Alpha2Code{
		Code:    "TH",
		Status:  1,
		Country: "Thailand",
	}
	TI = Alpha2Code{
		Code:    "TI",
		Status:  7,
		Country: "",
	}
	TJ = Alpha2Code{
		Code:    "TJ",
		Status:  1,
		Country: "Tajikistan",
	}
	TK = Alpha2Code{
		Code:    "TK",
		Status:  1,
		Country: "Tokelau",
	}
	TL = Alpha2Code{
		Code:    "TL",
		Status:  1,
		Country: "Timor-Leste",
	}
	TM = Alpha2Code{
		Code:    "TM",
		Status:  1,
		Country: "Turkmenistan",
	}
	TN = Alpha2Code{
		Code:    "TN",
		Status:  1,
		Country: "Tunisia",
	}
	TO = Alpha2Code{
		Code:    "TO",
		Status:  1,
		Country: "Tonga",
	}
	TP = Alpha2Code{
		Code:    "TP",
		Status:  4,
		Country: "East Timor",
	}
	TQ = Alpha2Code{
		Code:    "TQ",
		Status:  7,
		Country: "",
	}
	TR = Alpha2Code{
		Code:    "TR",
		Status:  1,
		Country: "Türkiye",
	}
	TS = Alpha2Code{
		Code:    "TS",
		Status:  7,
		Country: "",
	}
	TT = Alpha2Code{
		Code:    "TT",
		Status:  1,
		Country: "Trinidad and Tobago",
	}
	TU = Alpha2Code{
		Code:    "TU",
		Status:  7,
		Country: "",
	}
	TV = Alpha2Code{
		Code:    "TV",
		Status:  1,
		Country: "Tuvalu",
	}
	TW = Alpha2Code{
		Code:    "TW",
		Status:  1,
		Country: "Taiwan (Province of China)",
	}
	TX = Alpha2Code{
		Code:    "TX",
		Status:  7,
		Country: "",
	}
	TY = Alpha2Code{
		Code:    "TY",
		Status:  7,
		Country: "",
	}
	TZ = Alpha2Code{
		Code:    "TZ",
		Status:  1,
		Country: "Tanzania, the United Republic of",
	}
	UA = Alpha2Code{
		Code:    "UA",
		Status:  1,
		Country: "Ukraine",
	}
	UB = Alpha2Code{
		Code:    "UB",
		Status:  7,
		Country: "",
	}
	UC = Alpha2Code{
		Code:    "UC",
		Status:  7,
		Country: "",
	}
	UD = Alpha2Code{
		Code:    "UD",
		Status:  7,
		Country: "",
	}
	UE = Alpha2Code{
		Code:    "UE",
		Status:  7,
		Country: "",
	}
	UF = Alpha2Code{
		Code:    "UF",
		Status:  7,
		Country: "",
	}
	UG = Alpha2Code{
		Code:    "UG",
		Status:  1,
		Country: "Uganda",
	}
	UH = Alpha2Code{
		Code:    "UH",
		Status:  7,
		Country: "",
	}
	UI = Alpha2Code{
		Code:    "UI",
		Status:  7,
		Country: "",
	}
	UJ = Alpha2Code{
		Code:    "UJ",
		Status:  7,
		Country: "",
	}
	UK = Alpha2Code{
		Code:    "UK",
		Status:  3,
		Country: "United Kingdom",
	}
	UL = Alpha2Code{
		Code:    "UL",
		Status:  7,
		Country: "",
	}
	UM = Alpha2Code{
		Code:    "UM",
		Status:  1,
		Country: "United States Minor Outlying Islands (the)",
	}
	UN = Alpha2Code{
		Code:    "UN",
		Status:  3,
		Country: "",
	}
	UO = Alpha2Code{
		Code:    "UO",
		Status:  7,
		Country: "",
	}
	UP = Alpha2Code{
		Code:    "UP",
		Status:  7,
		Country: "",
	}
	UQ = Alpha2Code{
		Code:    "UQ",
		Status:  7,
		Country: "",
	}
	UR = Alpha2Code{
		Code:    "UR",
		Status:  7,
		Country: "",
	}
	US = Alpha2Code{
		Code:    "US",
		Status:  1,
		Country: "United States of America (the)",
	}
	UT = Alpha2Code{
		Code:    "UT",
		Status:  7,
		Country: "",
	}
	UU = Alpha2Code{
		Code:    "UU",
		Status:  7,
		Country: "",
	}
	UV = Alpha2Code{
		Code:    "UV",
		Status:  7,
		Country: "",
	}
	UW = Alpha2Code{
		Code:    "UW",
		Status:  7,
		Country: "",
	}
	UX = Alpha2Code{
		Code:    "UX",
		Status:  7,
		Country: "",
	}
	UY = Alpha2Code{
		Code:    "UY",
		Status:  1,
		Country: "Uruguay",
	}
	UZ = Alpha2Code{
		Code:    "UZ",
		Status:  1,
		Country: "Uzbekistan",
	}
	VA = Alpha2Code{
		Code:    "VA",
		Status:  1,
		Country: "Holy See (the)",
	}
	VB = Alpha2Code{
		Code:    "VB",
		Status:  7,
		Country: "",
	}
	VC = Alpha2Code{
		Code:    "VC",
		Status:  1,
		Country: "Saint Vincent and the Grenadines",
	}
	VD = Alpha2Code{
		Code:    "VD",
		Status:  5,
		Country: "Viet-Nam, Democratic Republic of",
	}
	VE = Alpha2Code{
		Code:    "VE",
		Status:  1,
		Country: "Venezuela (Bolivarian Republic of)",
	}
	VF = Alpha2Code{
		Code:    "VF",
		Status:  7,
		Country: "",
	}
	VG = Alpha2Code{
		Code:    "VG",
		Status:  1,
		Country: "Virgin Islands (British)",
	}
	VH = Alpha2Code{
		Code:    "VH",
		Status:  7,
		Country: "",
	}
	VI = Alpha2Code{
		Code:    "VI",
		Status:  1,
		Country: "Virgin Islands (U.S.)",
	}
	VJ = Alpha2Code{
		Code:    "VJ",
		Status:  7,
		Country: "",
	}
	VK = Alpha2Code{
		Code:    "VK",
		Status:  7,
		Country: "",
	}
	VL = Alpha2Code{
		Code:    "VL",
		Status:  7,
		Country: "",
	}
	VM = Alpha2Code{
		Code:    "VM",
		Status:  7,
		Country: "",
	}
	VN = Alpha2Code{
		Code:    "VN",
		Status:  1,
		Country: "Viet Nam",
	}
	VO = Alpha2Code{
		Code:    "VO",
		Status:  7,
		Country: "",
	}
	VP = Alpha2Code{
		Code:    "VP",
		Status:  7,
		Country: "",
	}
	VQ = Alpha2Code{
		Code:    "VQ",
		Status:  7,
		Country: "",
	}
	VR = Alpha2Code{
		Code:    "VR",
		Status:  7,
		Country: "",
	}
	VS = Alpha2Code{
		Code:    "VS",
		Status:  7,
		Country: "",
	}
	VT = Alpha2Code{
		Code:    "VT",
		Status:  7,
		Country: "",
	}
	VU = Alpha2Code{
		Code:    "VU",
		Status:  1,
		Country: "Vanuatu",
	}
	VV = Alpha2Code{
		Code:    "VV",
		Status:  7,
		Country: "",
	}
	VW = Alpha2Code{
		Code:    "VW",
		Status:  7,
		Country: "",
	}
	VX = Alpha2Code{
		Code:    "VX",
		Status:  7,
		Country: "",
	}
	VY = Alpha2Code{
		Code:    "VY",
		Status:  7,
		Country: "",
	}
	VZ = Alpha2Code{
		Code:    "VZ",
		Status:  7,
		Country: "",
	}
	WA = Alpha2Code{
		Code:    "WA",
		Status:  7,
		Country: "",
	}
	WB = Alpha2Code{
		Code:    "WB",
		Status:  7,
		Country: "",
	}
	WC = Alpha2Code{
		Code:    "WC",
		Status:  7,
		Country: "",
	}
	WD = Alpha2Code{
		Code:    "WD",
		Status:  7,
		Country: "",
	}
	WE = Alpha2Code{
		Code:    "WE",
		Status:  7,
		Country: "",
	}
	WF = Alpha2Code{
		Code:    "WF",
		Status:  1,
		Country: "Wallis and Futuna",
	}
	WG = Alpha2Code{
		Code:    "WG",
		Status:  5,
		Country: "Grenada",
	}
	WH = Alpha2Code{
		Code:    "WH",
		Status:  7,
		Country: "",
	}
	WI = Alpha2Code{
		Code:    "WI",
		Status:  7,
		Country: "",
	}
	WJ = Alpha2Code{
		Code:    "WJ",
		Status:  7,
		Country: "",
	}
	WK = Alpha2Code{
		Code:    "WK",
		Status:  5,
		Country: "Wake Island",
	}
	WL = Alpha2Code{
		Code:    "WL",
		Status:  5,
		Country: "Saint Lucia",
	}
	WM = Alpha2Code{
		Code:    "WM",
		Status:  7,
		Country: "",
	}
	WN = Alpha2Code{
		Code:    "WN",
		Status:  7,
		Country: "",
	}
	WO = Alpha2Code{
		Code:    "WO",
		Status:  5,
		Country: "World Intellectual Property Organization",
	}
	WP = Alpha2Code{
		Code:    "WP",
		Status:  7,
		Country: "",
	}
	WQ = Alpha2Code{
		Code:    "WQ",
		Status:  7,
		Country: "",
	}
	WR = Alpha2Code{
		Code:    "WR",
		Status:  7,
		Country: "",
	}
	WS = Alpha2Code{
		Code:    "WS",
		Status:  1,
		Country: "Samoa",
	}
	WT = Alpha2Code{
		Code:    "WT",
		Status:  7,
		Country: "",
	}
	WU = Alpha2Code{
		Code:    "WU",
		Status:  7,
		Country: "",
	}
	WV = Alpha2Code{
		Code:    "WV",
		Status:  5,
		Country: "Saint Vincent",
	}
	WW = Alpha2Code{
		Code:    "WW",
		Status:  7,
		Country: "",
	}
	WX = Alpha2Code{
		Code:    "WX",
		Status:  7,
		Country: "",
	}
	WY = Alpha2Code{
		Code:    "WY",
		Status:  7,
		Country: "",
	}
	WZ = Alpha2Code{
		Code:    "WZ",
		Status:  7,
		Country: "",
	}
	XA = Alpha2Code{
		Code:    "XA",
		Status:  2,
		Country: "",
	}
	XB = Alpha2Code{
		Code:    "XB",
		Status:  2,
		Country: "",
	}
	XC = Alpha2Code{
		Code:    "XC",
		Status:  2,
		Country: "",
	}
	XD = Alpha2Code{
		Code:    "XD",
		Status:  2,
		Country: "",
	}
	XE = Alpha2Code{
		Code:    "XE",
		Status:  2,
		Country: "",
	}
	XF = Alpha2Code{
		Code:    "XF",
		Status:  2,
		Country: "",
	}
	XG = Alpha2Code{
		Code:    "XG",
		Status:  2,
		Country: "",
	}
	XH = Alpha2Code{
		Code:    "XH",
		Status:  2,
		Country: "",
	}
	XI = Alpha2Code{
		Code:    "XI",
		Status:  2,
		Country: "",
	}
	XJ = Alpha2Code{
		Code:    "XJ",
		Status:  2,
		Country: "",
	}
	XK = Alpha2Code{
		Code:    "XK",
		Status:  2,
		Country: "",
	}
	XL = Alpha2Code{
		Code:    "XL",
		Status:  2,
		Country: "",
	}
	XM = Alpha2Code{
		Code:    "XM",
		Status:  2,
		Country: "",
	}
	XN = Alpha2Code{
		Code:    "XN",
		Status:  2,
		Country: "",
	}
	XO = Alpha2Code{
		Code:    "XO",
		Status:  2,
		Country: "",
	}
	XP = Alpha2Code{
		Code:    "XP",
		Status:  2,
		Country: "",
	}
	XQ = Alpha2Code{
		Code:    "XQ",
		Status:  2,
		Country: "",
	}
	XR = Alpha2Code{
		Code:    "XR",
		Status:  2,
		Country: "",
	}
	XS = Alpha2Code{
		Code:    "XS",
		Status:  2,
		Country: "",
	}
	XT = Alpha2Code{
		Code:    "XT",
		Status:  2,
		Country: "",
	}
	XU = Alpha2Code{
		Code:    "XU",
		Status:  2,
		Country: "",
	}
	XV = Alpha2Code{
		Code:    "XV",
		Status:  2,
		Country: "",
	}
	XW = Alpha2Code{
		Code:    "XW",
		Status:  2,
		Country: "",
	}
	XX = Alpha2Code{
		Code:    "XX",
		Status:  2,
		Country: "",
	}
	XY = Alpha2Code{
		Code:    "XY",
		Status:  2,
		Country: "",
	}
	XZ = Alpha2Code{
		Code:    "XZ",
		Status:  2,
		Country: "",
	}
	YA = Alpha2Code{
		Code:    "YA",
		Status:  7,
		Country: "",
	}
	YB = Alpha2Code{
		Code:    "YB",
		Status:  7,
		Country: "",
	}
	YC = Alpha2Code{
		Code:    "YC",
		Status:  7,
		Country: "",
	}
	YD = Alpha2Code{
		Code:    "YD",
		Status:  5,
		Country: "Yemen, Democratic",
	}
	YE = Alpha2Code{
		Code:    "YE",
		Status:  1,
		Country: "Yemen",
	}
	YF = Alpha2Code{
		Code:    "YF",
		Status:  7,
		Country: "",
	}
	YG = Alpha2Code{
		Code:    "YG",
		Status:  7,
		Country: "",
	}
	YH = Alpha2Code{
		Code:    "YH",
		Status:  7,
		Country: "",
	}
	YI = Alpha2Code{
		Code:    "YI",
		Status:  7,
		Country: "",
	}
	YJ = Alpha2Code{
		Code:    "YJ",
		Status:  7,
		Country: "",
	}
	YK = Alpha2Code{
		Code:    "YK",
		Status:  7,
		Country: "",
	}
	YL = Alpha2Code{
		Code:    "YL",
		Status:  7,
		Country: "",
	}
	YM = Alpha2Code{
		Code:    "YM",
		Status:  7,
		Country: "",
	}
	YN = Alpha2Code{
		Code:    "YN",
		Status:  7,
		Country: "",
	}
	YO = Alpha2Code{
		Code:    "YO",
		Status:  7,
		Country: "",
	}
	YP = Alpha2Code{
		Code:    "YP",
		Status:  7,
		Country: "",
	}
	YQ = Alpha2Code{
		Code:    "YQ",
		Status:  7,
		Country: "",
	}
	YR = Alpha2Code{
		Code:    "YR",
		Status:  7,
		Country: "",
	}
	YS = Alpha2Code{
		Code:    "YS",
		Status:  7,
		Country: "",
	}
	YT = Alpha2Code{
		Code:    "YT",
		Status:  1,
		Country: "Mayotte",
	}
	YU = Alpha2Code{
		Code:    "YU",
		Status:  4,
		Country: "Yugoslavia",
	}
	YV = Alpha2Code{
		Code:    "YV",
		Status:  5,
		Country: "Venezuela",
	}
	YW = Alpha2Code{
		Code:    "YW",
		Status:  7,
		Country: "",
	}
	YX = Alpha2Code{
		Code:    "YX",
		Status:  7,
		Country: "",
	}
	YY = Alpha2Code{
		Code:    "YY",
		Status:  7,
		Country: "",
	}
	YZ = Alpha2Code{
		Code:    "YZ",
		Status:  7,
		Country: "",
	}
	ZA = Alpha2Code{
		Code:    "ZA",
		Status:  1,
		Country: "South Africa",
	}
	ZB = Alpha2Code{
		Code:    "ZB",
		Status:  7,
		Country: "",
	}
	ZC = Alpha2Code{
		Code:    "ZC",
		Status:  7,
		Country: "",
	}
	ZD = Alpha2Code{
		Code:    "ZD",
		Status:  7,
		Country: "",
	}
	ZE = Alpha2Code{
		Code:    "ZE",
		Status:  7,
		Country: "",
	}
	ZF = Alpha2Code{
		Code:    "ZF",
		Status:  7,
		Country: "",
	}
	ZG = Alpha2Code{
		Code:    "ZG",
		Status:  7,
		Country: "",
	}
	ZH = Alpha2Code{
		Code:    "ZH",
		Status:  7,
		Country: "",
	}
	ZI = Alpha2Code{
		Code:    "ZI",
		Status:  7,
		Country: "",
	}
	ZJ = Alpha2Code{
		Code:    "ZJ",
		Status:  7,
		Country: "",
	}
	ZK = Alpha2Code{
		Code:    "ZK",
		Status:  7,
		Country: "",
	}
	ZL = Alpha2Code{
		Code:    "ZL",
		Status:  7,
		Country: "",
	}
	ZM = Alpha2Code{
		Code:    "ZM",
		Status:  1,
		Country: "Zambia",
	}
	ZN = Alpha2Code{
		Code:    "ZN",
		Status:  7,
		Country: "",
	}
	ZO = Alpha2Code{
		Code:    "ZO",
		Status:  7,
		Country: "",
	}
	ZP = Alpha2Code{
		Code:    "ZP",
		Status:  7,
		Country: "",
	}
	ZQ = Alpha2Code{
		Code:    "ZQ",
		Status:  7,
		Country: "",
	}
	ZR = Alpha2Code{
		Code:    "ZR",
		Status:  4,
		Country: "Zaire",
	}
	ZS = Alpha2Code{
		Code:    "ZS",
		Status:  7,
		Country: "",
	}
	ZT = Alpha2Code{
		Code:    "ZT",
		Status:  7,
		Country: "",
	}
	ZU = Alpha2Code{
		Code:    "ZU",
		Status:  7,
		Country: "",
	}
	ZV = Alpha2Code{
		Code:    "ZV",
		Status:  7,
		Country: "",
	}
	ZW = Alpha2Code{
		Code:    "ZW",
		Status:  1,
		Country: "Zimbabwe",
	}
	ZX = Alpha2Code{
		Code:    "ZX",
		Status:  7,
		Country: "",
	}
	ZY = Alpha2Code{
		Code:    "ZY",
		Status:  7,
		Country: "",
	}
	ZZ = Alpha2Code{
		Code:    "ZZ",
		Status:  2,
		Country: "",
	}
)

var alpha2Codes = map[string]Alpha2Code{
	"AA": AA,
	"AB": AB,
	"AC": AC,
	"AD": AD,
	"AE": AE,
	"AF": AF,
	"AG": AG,
	"AH": AH,
	"AI": AI,
	"AJ": AJ,
	"AK": AK,
	"AL": AL,
	"AM": AM,
	"AN": AN,
	"AO": AO,
	"AP": AP,
	"AQ": AQ,
	"AR": AR,
	"AS": AS,
	"AT": AT,
	"AU": AU,
	"AV": AV,
	"AW": AW,
	"AX": AX,
	"AY": AY,
	"AZ": AZ,
	"BA": BA,
	"BB": BB,
	"BC": BC,
	"BD": BD,
	"BE": BE,
	"BF": BF,
	"BG": BG,
	"BH": BH,
	"BI": BI,
	"BJ": BJ,
	"BK": BK,
	"BL": BL,
	"BM": BM,
	"BN": BN,
	"BO": BO,
	"BP": BP,
	"BQ": BQ,
	"BR": BR,
	"BS": BS,
	"BT": BT,
	"BU": BU,
	"BV": BV,
	"BW": BW,
	"BX": BX,
	"BY": BY,
	"BZ": BZ,
	"CA": CA,
	"CB": CB,
	"CC": CC,
	"CD": CD,
	"CE": CE,
	"CF": CF,
	"CG": CG,
	"CH": CH,
	"CI": CI,
	"CJ": CJ,
	"CK": CK,
	"CL": CL,
	"CM": CM,
	"CN": CN,
	"CO": CO,
	"CP": CP,
	"CQ": CQ,
	"CR": CR,
	"CS": CS,
	"CT": CT,
	"CU": CU,
	"CV": CV,
	"CW": CW,
	"CX": CX,
	"CY": CY,
	"CZ": CZ,
	"DA": DA,
	"DB": DB,
	"DC": DC,
	"DD": DD,
	"DE": DE,
	"DF": DF,
	"DG": DG,
	"DH": DH,
	"DI": DI,
	"DJ": DJ,
	"DK": DK,
	"DL": DL,
	"DM": DM,
	"DN": DN,
	"DO": DO,
	"DP": DP,
	"DQ": DQ,
	"DR": DR,
	"DS": DS,
	"DT": DT,
	"DU": DU,
	"DV": DV,
	"DW": DW,
	"DX": DX,
	"DY": DY,
	"DZ": DZ,
	"EA": EA,
	"EB": EB,
	"EC": EC,
	"ED": ED,
	"EE": EE,
	"EF": EF,
	"EG": EG,
	"EH": EH,
	"EI": EI,
	"EJ": EJ,
	"EK": EK,
	"EL": EL,
	"EM": EM,
	"EN": EN,
	"EO": EO,
	"EP": EP,
	"EQ": EQ,
	"ER": ER,
	"ES": ES,
	"ET": ET,
	"EU": EU,
	"EV": EV,
	"EW": EW,
	"EX": EX,
	"EY": EY,
	"EZ": EZ,
	"FA": FA,
	"FB": FB,
	"FC": FC,
	"FD": FD,
	"FE": FE,
	"FF": FF,
	"FG": FG,
	"FH": FH,
	"FI": FI,
	"FJ": FJ,
	"FK": FK,
	"FL": FL,
	"FM": FM,
	"FN": FN,
	"FO": FO,
	"FP": FP,
	"FQ": FQ,
	"FR": FR,
	"FS": FS,
	"FT": FT,
	"FU": FU,
	"FV": FV,
	"FW": FW,
	"FX": FX,
	"FY": FY,
	"FZ": FZ,
	"GA": GA,
	"GB": GB,
	"GC": GC,
	"GD": GD,
	"GE": GE,
	"GF": GF,
	"GG": GG,
	"GH": GH,
	"GI": GI,
	"GJ": GJ,
	"GK": GK,
	"GL": GL,
	"GM": GM,
	"GN": GN,
	"GO": GO,
	"GP": GP,
	"GQ": GQ,
	"GR": GR,
	"GS": GS,
	"GT": GT,
	"GU": GU,
	"GV": GV,
	"GW": GW,
	"GX": GX,
	"GY": GY,
	"GZ": GZ,
	"HA": HA,
	"HB": HB,
	"HC": HC,
	"HD": HD,
	"HE": HE,
	"HF": HF,
	"HG": HG,
	"HH": HH,
	"HI": HI,
	"HJ": HJ,
	"HK": HK,
	"HL": HL,
	"HM": HM,
	"HN": HN,
	"HO": HO,
	"HP": HP,
	"HQ": HQ,
	"HR": HR,
	"HS": HS,
	"HT": HT,
	"HU": HU,
	"HV": HV,
	"HW": HW,
	"HX": HX,
	"HY": HY,
	"HZ": HZ,
	"IA": IA,
	"IB": IB,
	"IC": IC,
	"ID": ID,
	"IE": IE,
	"IF": IF,
	"IG": IG,
	"IH": IH,
	"II": II,
	"IJ": IJ,
	"IK": IK,
	"IL": IL,
	"IM": IM,
	"IN": IN,
	"IO": IO,
	"IP": IP,
	"IQ": IQ,
	"IR": IR,
	"IS": IS,
	"IT": IT,
	"IU": IU,
	"IV": IV,
	"IW": IW,
	"IX": IX,
	"IY": IY,
	"IZ": IZ,
	"JA": JA,
	"JB": JB,
	"JC": JC,
	"JD": JD,
	"JE": JE,
	"JF": JF,
	"JG": JG,
	"JH": JH,
	"JI": JI,
	"JJ": JJ,
	"JK": JK,
	"JL": JL,
	"JM": JM,
	"JN": JN,
	"JO": JO,
	"JP": JP,
	"JQ": JQ,
	"JR": JR,
	"JS": JS,
	"JT": JT,
	"JU": JU,
	"JV": JV,
	"JW": JW,
	"JX": JX,
	"JY": JY,
	"JZ": JZ,
	"KA": KA,
	"KB": KB,
	"KC": KC,
	"KD": KD,
	"KE": KE,
	"KF": KF,
	"KG": KG,
	"KH": KH,
	"KI": KI,
	"KJ": KJ,
	"KK": KK,
	"KL": KL,
	"KM": KM,
	"KN": KN,
	"KO": KO,
	"KP": KP,
	"KQ": KQ,
	"KR": KR,
	"KS": KS,
	"KT": KT,
	"KU": KU,
	"KV": KV,
	"KW": KW,
	"KX": KX,
	"KY": KY,
	"KZ": KZ,
	"LA": LA,
	"LB": LB,
	"LC": LC,
	"LD": LD,
	"LE": LE,
	"LF": LF,
	"LG": LG,
	"LH": LH,
	"LI": LI,
	"LJ": LJ,
	"LK": LK,
	"LL": LL,
	"LM": LM,
	"LN": LN,
	"LO": LO,
	"LP": LP,
	"LQ": LQ,
	"LR": LR,
	"LS": LS,
	"LT": LT,
	"LU": LU,
	"LV": LV,
	"LW": LW,
	"LX": LX,
	"LY": LY,
	"LZ": LZ,
	"MA": MA,
	"MB": MB,
	"MC": MC,
	"MD": MD,
	"ME": ME,
	"MF": MF,
	"MG": MG,
	"MH": MH,
	"MI": MI,
	"MJ": MJ,
	"MK": MK,
	"ML": ML,
	"MM": MM,
	"MN": MN,
	"MO": MO,
	"MP": MP,
	"MQ": MQ,
	"MR": MR,
	"MS": MS,
	"MT": MT,
	"MU": MU,
	"MV": MV,
	"MW": MW,
	"MX": MX,
	"MY": MY,
	"MZ": MZ,
	"NA": NA,
	"NB": NB,
	"NC": NC,
	"ND": ND,
	"NE": NE,
	"NF": NF,
	"NG": NG,
	"NH": NH,
	"NI": NI,
	"NJ": NJ,
	"NK": NK,
	"NL": NL,
	"NM": NM,
	"NN": NN,
	"NO": NO,
	"NP": NP,
	"NQ": NQ,
	"NR": NR,
	"NS": NS,
	"NT": NT,
	"NU": NU,
	"NV": NV,
	"NW": NW,
	"NX": NX,
	"NY": NY,
	"NZ": NZ,
	"OA": OA,
	"OB": OB,
	"OC": OC,
	"OD": OD,
	"OE": OE,
	"OF": OF,
	"OG": OG,
	"OH": OH,
	"OI": OI,
	"OJ": OJ,
	"OK": OK,
	"OL": OL,
	"OM": OM,
	"ON": ON,
	"OO": OO,
	"OP": OP,
	"OQ": OQ,
	"OR": OR,
	"OS": OS,
	"OT": OT,
	"OU": OU,
	"OV": OV,
	"OW": OW,
	"OX": OX,
	"OY": OY,
	"OZ": OZ,
	"PA": PA,
	"PB": PB,
	"PC": PC,
	"PD": PD,
	"PE": PE,
	"PF": PF,
	"PG": PG,
	"PH": PH,
	"PI": PI,
	"PJ": PJ,
	"PK": PK,
	"PL": PL,
	"PM": PM,
	"PN": PN,
	"PO": PO,
	"PP": PP,
	"PQ": PQ,
	"PR": PR,
	"PS": PS,
	"PT": PT,
	"PU": PU,
	"PV": PV,
	"PW": PW,
	"PX": PX,
	"PY": PY,
	"PZ": PZ,
	"QA": QA,
	"QB": QB,
	"QC": QC,
	"QD": QD,
	"QE": QE,
	"QF": QF,
	"QG": QG,
	"QH": QH,
	"QI": QI,
	"QJ": QJ,
	"QK": QK,
	"QL": QL,
	"QM": QM,
	"QN": QN,
	"QO": QO,
	"QP": QP,
	"QQ": QQ,
	"QR": QR,
	"QS": QS,
	"QT": QT,
	"QU": QU,
	"QV": QV,
	"QW": QW,
	"QX": QX,
	"QY": QY,
	"QZ": QZ,
	"RA": RA,
	"RB": RB,
	"RC": RC,
	"RD": RD,
	"RE": RE,
	"RF": RF,
	"RG": RG,
	"RH": RH,
	"RI": RI,
	"RJ": RJ,
	"RK": RK,
	"RL": RL,
	"RM": RM,
	"RN": RN,
	"RO": RO,
	"RP": RP,
	"RQ": RQ,
	"RR": RR,
	"RS": RS,
	"RT": RT,
	"RU": RU,
	"RV": RV,
	"RW": RW,
	"RX": RX,
	"RY": RY,
	"RZ": RZ,
	"SA": SA,
	"SB": SB,
	"SC": SC,
	"SD": SD,
	"SE": SE,
	"SF": SF,
	"SG": SG,
	"SH": SH,
	"SI": SI,
	"SJ": SJ,
	"SK": SK,
	"SL": SL,
	"SM": SM,
	"SN": SN,
	"SO": SO,
	"SP": SP,
	"SQ": SQ,
	"SR": SR,
	"SS": SS,
	"ST": ST,
	"SU": SU,
	"SV": SV,
	"SW": SW,
	"SX": SX,
	"SY": SY,
	"SZ": SZ,
	"TA": TA,
	"TB": TB,
	"TC": TC,
	"TD": TD,
	"TE": TE,
	"TF": TF,
	"TG": TG,
	"TH": TH,
	"TI": TI,
	"TJ": TJ,
	"TK": TK,
	"TL": TL,
	"TM": TM,
	"TN": TN,
	"TO": TO,
	"TP": TP,
	"TQ": TQ,
	"TR": TR,
	"TS": TS,
	"TT": TT,
	"TU": TU,
	"TV": TV,
	"TW": TW,
	"TX": TX,
	"TY": TY,
	"TZ": TZ,
	"UA": UA,
	"UB": UB,
	"UC": UC,
	"UD": UD,
	"UE": UE,
	"UF": UF,
	"UG": UG,
	"UH": UH,
	"UI": UI,
	"UJ": UJ,
	"UK": UK,
	"UL": UL,
	"UM": UM,
	"UN": UN,
	"UO": UO,
	"UP": UP,
	"UQ": UQ,
	"UR": UR,
	"US": US,
	"UT": UT,
	"UU": UU,
	"UV": UV,
	"UW": UW,
	"UX": UX,
	"UY": UY,
	"UZ": UZ,
	"VA": VA,
	"VB": VB,
	"VC": VC,
	"VD": VD,
	"VE": VE,
	"VF": VF,
	"VG": VG,
	"VH": VH,
	"VI": VI,
	"VJ": VJ,
	"VK": VK,
	"VL": VL,
	"VM": VM,
	"VN": VN,
	"VO": VO,
	"VP": VP,
	"VQ": VQ,
	"VR": VR,
	"VS": VS,
	"VT": VT,
	"VU": VU,
	"VV": VV,
	"VW": VW,
	"VX": VX,
	"VY": VY,
	"VZ": VZ,
	"WA": WA,
	"WB": WB,
	"WC": WC,
	"WD": WD,
	"WE": WE,
	"WF": WF,
	"WG": WG,
	"WH": WH,
	"WI": WI,
	"WJ": WJ,
	"WK": WK,
	"WL": WL,
	"WM": WM,
	"WN": WN,
	"WO": WO,
	"WP": WP,
	"WQ": WQ,
	"WR": WR,
	"WS": WS,
	"WT": WT,
	"WU": WU,
	"WV": WV,
	"WW": WW,
	"WX": WX,
	"WY": WY,
	"WZ": WZ,
	"XA": XA,
	"XB": XB,
	"XC": XC,
	"XD": XD,
	"XE": XE,
	"XF": XF,
	"XG": XG,
	"XH": XH,
	"XI": XI,
	"XJ": XJ,
	"XK": XK,
	"XL": XL,
	"XM": XM,
	"XN": XN,
	"XO": XO,
	"XP": XP,
	"XQ": XQ,
	"XR": XR,
	"XS": XS,
	"XT": XT,
	"XU": XU,
	"XV": XV,
	"XW": XW,
	"XX": XX,
	"XY": XY,
	"XZ": XZ,
	"YA": YA,
	"YB": YB,
	"YC": YC,
	"YD": YD,
	"YE": YE,
	"YF": YF,
	"YG": YG,
	"YH": YH,
	"YI": YI,
	"YJ": YJ,
	"YK": YK,
	"YL": YL,
	"YM": YM,
	"YN": YN,
	"YO": YO,
	"YP": YP,
	"YQ": YQ,
	"YR": YR,
	"YS": YS,
	"YT": YT,
	"YU": YU,
	"YV": YV,
	"YW": YW,
	"YX": YX,
	"YY": YY,
	"YZ": YZ,
	"ZA": ZA,
	"ZB": ZB,
	"ZC": ZC,
	"ZD": ZD,
	"ZE": ZE,
	"ZF": ZF,
	"ZG": ZG,
	"ZH": ZH,
	"ZI": ZI,
	"ZJ": ZJ,
	"ZK": ZK,
	"ZL": ZL,
	"ZM": ZM,
	"ZN": ZN,
	"ZO": ZO,
	"ZP": ZP,
	"ZQ": ZQ,
	"ZR": ZR,
	"ZS": ZS,
	"ZT": ZT,
	"ZU": ZU,
	"ZV": ZV,
	"ZW": ZW,
	"ZX": ZX,
	"ZY": ZY,
	"ZZ": ZZ,
}
